BACKEND_VOLUME := Y
BACKEND_BRIGHTNESS := Y
BACKEND_POWEROFF := Y
BACKEND_REBOOT := Y
BACKEND_TVOUT := Y
BACKEND_KILL := Y
BACKEND_SCREENSHOT := Y

# Current OpenDingux/GCW0 doesn't support suspend
# BACKEND_SUSPEND := Y

CFLAGS+=-DMIN_BRIGHTNESS=1

CROSS_COMPILE?=mipsel-gcw0-linux-uclibc-
